import type {Metadata} from 'next';
import './globals.css';
import { PatchNotes } from '@/components/patch-notes';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

const Footer = () => {
  const currentYear = new Date().getFullYear();
  const version = "0.0.0.7"; 

  return (
    <footer className="w-full bg-background border-t border-border mt-auto">
      <div className="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row justify-between items-center text-sm text-muted-foreground">
        <div className='flex items-center gap-4'>
            <p>Versão {version}</p>
            <PatchNotes />
        </div>
        <p>
          Criado por:{' '}
          <a
            href="https://www.instagram.com/leo.lemos992/"
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-primary hover:underline"
          >
            @leo.lemos992
          </a>
        </p>
      </div>
    </footer>
  );
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased flex flex-col min-h-screen">
        <div className='flex-grow'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
